name: Kindle4rss auto deliver

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: python main.py -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
